name: CI

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Test Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false

  push:
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - uses: actions/checkout@v2.3.4
        name: Checkout Repo
        with:
          fetch-depth: "0"

      - uses: actions/setup-node@v2.3.0
        name: Setup Node
        with:
          node-version: "15"

      - name: "Automated Version Bump"
        id: version-bump
        uses: "phips28/gh-action-bump-version@master"
        with:
          skip-tag: "true"
          minor-wording: "!MINOR"
          major-wording: "!MAJOR"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.35.0
        id: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to registry
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            latest
            ${{ steps.tag.outputs.new_tag }}
