# Workflow to test docker builds and publish to GitHub Container Registry when committing to master
name: CI

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Test Build
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: false

  push:
    # Ensure test job passes before pushing image.
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - uses: actions/checkout@v3
        name: Checkout Repo
        with:
          fetch-depth: "0"

      - uses: actions/setup-node@v3.5.0
        name: Setup Node
        with:
          node-version: "15"

      - name: "Automated Version Bump"
        id: version-bump
        uses: "phips28/gh-action-bump-version@master"
        with:
          skip-tag: "true"
          minor-wording: "!MINOR"
          major-wording: "!MAJOR"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.52.0
        id: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/zozman/blaseball-buzz:${{ steps.tag.outputs.new_tag }}
            ghcr.io/zozman/blaseball-buzz:latest

      #- uses: zozman/docker-build-push@useBuildxCommand
      #  name: Build & push Docker image
      #  with:
      #    image: blaseball-buzz
      #    tags: ${{ steps.tag.outputs.new_tag }}, latest
      #    registry: ghcr.io
      #    dockerfile: Dockerfile
      #    useBuildxCommand: true
      #    platform: linux/amd64,linux/arm64
      #    username: ${{ github.actor }}
      #    password: ${{ secrets.GITHUB_TOKEN }}
